import LocalizedStrings from 'react-native-localization';

export const Strings = new LocalizedStrings({
  it: {
    exceptions_general_error: "C'è stato un errore, riprova",
    exceptions_insert_result: 'Inserisci un risultato',
    exceptions_insert_metric: 'Inserisci una metrica',
    exceptions_insert_date: 'Inserisci una data',
    exceptions_permission_camera: 'Permessi Fotocamera mancanti',
    exceptions_permission_library: 'Permessi Libreria mancanti',
    exceptions_permission_desc:
      'Clicca quì per andare alle impostazioni e dare i permessi',
    exceptions_no_title_or_media: 'Aggiungi un titolo e almeno un media',
    exceptions_no_data_or_image: 'Aggiungi una data e almeno una foto',
    exceptions_insert_all_values: 'Inseirsci tutti i valori',
    exceptions_generic: 'Qualcosa è andato storto',
    btn_back: 'Indietro',
    btn_next: 'Prossimo',
    btn_done: 'Fatto',
    label_log_in: 'Log in',
    label_to_complete: 'Da fare',
    label_expired: 'Scaduti',
    label_done: 'Completati',
    label_profile: 'Profilo',
    label_edit_profile: 'Modifica il profilo',
    label_save: 'Salva',
    label_undo: 'Annulla',
    label_personal_informations: 'Informazioni personali',
    label_settings: 'Impostazioni',
    label_name: 'Nome',
    label_surname: 'Cognome',
    label_email: 'Email',
    label_notifications: 'Notifiche',
    label_reminders: 'Promemoria',
    label_logout: 'Logout',
    label_workout_done: 'Workout completato',
    label_workout_todo: 'Sposta nei "Da fare"',
    label_yes: 'Sì',
    label_no: 'No',
    label_load_more_messages: 'Carica messaggi precedenti',
    label_loading: 'Invio in corso',
    label_update_app: "Aggiorna l'app",
    label_update_app_desc:
      "È necessario aggiornare l'app per continuare ad utilizzarla",
    label_update: 'Aggiorna',
    label_result: 'Risultato',
    label_results: 'Risultati',
    label_date: 'Data',
    label_insert_result: 'Inserisci un risultato',
    label_insert_date: 'Inserisci una data',
    label_insert_metric: 'Inserisci una metrica',
    label_add_metric_result: 'Aggiungi metrica',
    label_save_metric_result: 'Salva metrica',
    label_add_new_food: 'Aggiungi alimento',
    label_metric_result_added: 'Risultato aggiunto correttamente',
    label_no_result: 'Nessun risultato inserito',
    label_show_detail_history: 'Vedi dettagli storico',
    label_complete_history: 'Storico Completo',
    label_exercises: 'Esercizi',
    label_exercise: 'Esercizio',
    label_n_exercises: '{0} esercizi',
    label_execution: 'Esecuzione',
    label_informations: 'Informazioni',
    label_message: 'Messaggio',
    label_comments: 'Commenti',
    label_attachments: 'Allegati',
    label_attachment: 'Allegato',
    label_write_a_comment: 'Scrivi un commento',
    label_add_media: 'Aggiungi immagini/video',
    label_description: 'Descrizione',
    label_load_description: 'Carica una descrizione',
    label_load_multimedia: 'Carica multimedia',
    label_load_progress: 'Carica progressi',
    label_media_added: 'Multimedia caricati correttamente',
    label_progress_added: 'Progressi caricati correttamente',
    label_progress_deleted: 'Progresso eliminato',
    label_delete: 'Elimina',
    label_multimedia: 'Multimedia',
    label_progresses: 'Progressi',
    label_reservations: 'Prenotazioni',
    label_day_availability: 'Disponibilità giorno',
    label_add_progress: 'Nuovo progresso',
    label_metric: 'Metrica',
    label_metrics: 'Metriche',
    label_add: 'Aggiungi',
    label_front_photo: 'Foto frontale',
    label_side_photo: 'Foto laterale',
    label_back_photo: 'Foto di spalle',
    label_load_front_photo: 'Carica foto frontale',
    label_load_side_photo: 'Carica foto laterale',
    label_load_back_photo: 'Carica foto di spalle',
    label_medias_and_documents: 'Media e documenti',
    label_search: 'Cerca',
    label_search_exercise: 'Cerca esercizio',
    label_image: 'Immagine',
    label_video: 'Video',
    label_file: 'File',
    label_files: 'Files',
    label_set: 'Serie',
    label_add_set: 'Aggiungi serie',
    label_time: 'Tempo',
    label_ramp: 'Ramp',
    label_reps: 'Ripetizioni',
    label_reps_short: 'Reps',
    label_min: 'min',
    label_sec: 'sec',
    label_rest: 'Rec.',
    label_rest_long: 'Recupero',
    label_timer: 'Timer',
    label_no_rest: 'Nessuno',
    label_hide_execution: 'Chiudi esecuzione',
    label_notes: 'Note',
    label_workouts: 'Allenamenti',
    label_plan: 'PLAN',
    label_overall: 'Complessivi',
    label_all: 'Tutti',
    label_load: 'Carica',
    label_load_more: 'Carica altro',
    label_nutrition: 'Nutrizione',
    label_nutritional_advice: 'Consigli nutrizionali',
    label_meal_plans: 'Piani alimentari',
    label_meal_plan: 'Piano alimentare',
    label_meal_plan_info: 'Informazioni piano',
    label_macros: 'Macronutrienti',
    label_shopping_list: 'Lista della spesa',
    label_weights_history: 'Storico pesi',
    label_add_weight_result: 'Aggiungi Carico',
    label_add_note: 'Aggiungi Nota',
    label_save_weight_result: 'Salva Carico',
    label_weight_result_added: 'Carichi registrati correttamente',
    label_weight_kg: 'Peso (Kg)',
    label_insert_note: 'Inserisci Nota',
    label_insert_general_note: "Inserisci note generali dell'esercizio",
    label_retry: 'Riprova',
    label_language: 'Lingua',
    label_superset: 'Superserie',
    label_forgotten_password: 'Password dimenticata?',
    label_confirm: 'Conferma',
    label_send: 'Invia',
    label_contact: 'Contatta',
    label_start_workout: 'Inizia allenamento',
    label_pause: 'Pausa',
    label_play: 'Play',
    label_finish: 'Termina',
    label_close: 'Chiudi',
    label_work: 'Lavoro: ',
    label_rest_two_points: 'Recupero: ',
    label_start_exercise: 'Inizia esercizio',
    label_new_set: 'Nuovo set',
    label_save_history: 'Salva nello storico',
    label_recovers: 'Recupera Workout',
    label_insert_food_name: 'Inserisci nome alimento',
    label_purchased: 'Acquistato',
    label_to_buy: 'Da acquistare',
    label_additional_note: 'Note aggiuntive',
    label_reserve: 'Prenota',
    label_reserved: 'Prenotato',
    label_reserved_plural: 'Prenotati',
    label_time_to_cancel_expired: 'Tempo per la\ncancellazione scaduto',
    label_time_to_booking_expired: 'Tempo per la\nprenotazione scaduto',
    label_sold_out: 'Posti esauriti',
    label_my_reservations: 'Le mie prenotazioni',
    label_week: 'Settimana',
    label_day: 'Giorno',
    label_start: 'Inizio',
    label_end: 'Fine',
    label_monday: 'Lunedì',
    label_tuesday: 'Martedì',
    label_wednesday: 'Mercoledì',
    label_thursday: 'Giovedì',
    label_friday: 'Venerdì',
    label_saturday: 'Sabato',
    label_sunday: 'Domenica',
    label_calories: 'Calorie',
    label_carbs: 'Carb.',
    label_proteins: 'Proteine',
    label_lipids: 'Grassi',
    label_or: 'oppure',
    label_from_visit: 'DA VISITA',
    label_compare: 'Confronta',
    label_compare_images: 'Confronta immagini',
    label_compare_images_slider: 'Confronta immagini slider',
    label_show_info: 'Mostra informazioni',
    label_hide_info: 'Nascondi informazioni',
    label_upload_attachment: 'Carica allegato',
    label_insert_message: 'Inserisci un messaggio',
    label_document: 'Documento',
    label_camera: 'Fotocamera',
    label_gallery_and_video: 'Foto e video',
    label_surveys: 'Questionari',
    label_survey: 'Questionario',
    label_discount_codes: 'Codici sconto',
    label_insert_value: 'Inserisci valore',
    label_survey_completed: 'Questionario completato correttamente',
    label_skip: 'Salta',
    label_fill_in_later: 'Compila in seguito',
    label_welcome: 'Benvenuto',
    label_check_in: 'Check In',
    label_fill_in_the_required_answers: 'Compila le risposte obbligarorie',
    label_specific: 'Specifico',
    label_not_editable: '(non modificabile)',
    label_very_easy: 'Molto facile',
    label_easy: 'Facile',
    label_medium: 'Medio',
    label_hard: 'Difficile',
    label_very_hard: 'Molto difficile',
    label_your_time: 'Il tuo tempo',
    label_chat: 'Chat',
    label_no_message: 'Nessun messaggio',
    label_personal: 'Personali',
    label_program: 'Programma',

    strings_profile_edit_success: 'Profilo salvato correttamente',
    strings_empty_to_do_workouts: 'Nessun allenamento in programma',
    strings_empty_meal_plans: 'Nessun piano alimentare assegnato',
    strings_empty_macros: 'Nessun macronutriente assegnato',
    strings_empty_completed_workouts: 'Nessun allenamento completato',
    strings_empty_executions: 'Nessuna esecuzione',
    strings_empty_reminders: 'Nessun promemoria',
    strings_confirm_mark_completed_workout:
      'Vuoi segnare il workout come completato?',
    strings_confirm_mark_todo_workout: 'Vuoi segnare il workout come da fare?',
    strings_confirm_delete_progress: 'Vuoi eliminare questi progressi?',
    strings_confirm_delete_result: 'Vuoi eliminare questo risultato?',
    strings_empty_metrics: 'Nessuna metrica',
    strings_empty_visits: 'Nessuna visita',
    strings_empty_media: 'Nessun file caricato',
    strings_unavailable_chat: 'Chat non disponibile',
    strings_empty_nutritional_advices: 'Nessun consiglio nutrizionale caricato',
    strings_empty_shopping_list: 'Nessun alimento inserito',
    strings_empty_progress: 'Nessun progresso caricato',
    strings_empty_info: 'Nessun informazione aggiuntiva',
    strings_empty_reservations: 'Nessuna prenotazione disponibile',
    strings_empty_programs: 'Nessun programma di allenamento assegnato',
    strings_empty_conversations: 'Nessuna conversazione',
    strings_empty_weight: 'Nessun carico inserito',
    strings_empty_weight_look_history:
      'Nessun carico inserito per questa modalità di esecuzione \n\n Consulta lo {0} in alto',
    strings_empty_note: 'Nessuna nota inserita',
    strings_empty_note_look_history:
      'Nessuna nota inserita per questa modalità di esecuzione \n\n Consulta lo {0} in alto',
    strings_other_workouts: 'Ci sono altri {0} workouts da fare',
    strings_other_workouts_info:
      'I workouts saranno visibili con il passare delle settimane',
    strings_confirm_add_weights_different_set:
      "Il numero dei Set inseriti è diverso da quelli dell'esercizio.\nVuoi inserirli comunque?",
    strings_confirm_delete_weights:
      'Sei sicuro di voler cancellare questi carichi?',
    strings_initial_state_error_desc:
      "C'è stato un problema durante l'inizializzatione dell'applicazione, riprova.",
    strings_forgotten_password_desc:
      'Ti invieremo una email per reimpostare la tua password',
    strings_email_recovery_sent_succesfull:
      'Email di ripristino password inviata',
    strings_disabled_user:
      'Sei stato disattivato dal tuo coach, contattalo per maggiori informazioni',
    strings_workouts_not_done:
      'Ci sono {0} workout che non hai completato, recuperali al più presto!',
    strings_workout_not_done:
      "C'è {0} workout che non hai completato, recuperalo al più presto!",
    strings_no_reservations_available_on_date:
      'Non ci sono prenotazioni disponibili per questa data',
    strings_write_reservation_message:
      'Lasciare vuoto per non inviare nessun messaggio',
    strings_empty_surveys: 'Nessun questionario',
    strings_empty_questions: 'Nessuna domanda',
    strings_how_did_you_find_the_workout: 'Come hai trovato l’allenamento?',
    strings_trim_video_error: 'I video ritagliati devono durare 60 secondi o meno.',
  },
  en: {
    exceptions_general_error: 'An error has occurred, please try again',
    exceptions_insert_result: 'Insert a result',
    exceptions_insert_metric: 'Insert a metric',
    exceptions_insert_date: 'Insert a date',
    exceptions_permission_camera: 'Missing camera permissions',
    exceptions_permission_library: 'Missing library permissions',
    exceptions_permission_desc:
      'Click here to go to settings and allow permissions',
    exceptions_no_title_or_media: 'Add a title and at least one media',
    exceptions_no_data_or_image: 'Add a date and at least one photo',
    exceptions_insert_all_values: 'Insert all values',
    exceptions_generic: 'Something went wrong',
    btn_back: 'Back',
    btn_next: 'Next',
    btn_done: 'Done',
    label_log_in: 'Log in',
    label_to_complete: 'To do',
    label_expired: 'Expired',
    label_done: 'Completed',
    label_profile: 'Profile',
    label_edit_profile: 'Edit profile',
    label_save: 'Save',
    label_undo: 'Cancel',
    label_personal_informations: 'Personal information',
    label_settings: 'Settings',
    label_name: 'Name',
    label_surname: 'Last name',
    label_email: 'Email',
    label_notifications: 'Notifications',
    label_reminders: 'Reminders',
    label_logout: 'Logout',
    label_workout_done: 'Complete workout',
    label_workout_todo: 'Move into "To do"',
    label_yes: 'Yes',
    label_no: 'No',
    label_load_more_messages: 'Load previous messages',
    label_loading: 'Uploading',
    label_update_app: 'Update the app',
    label_update_app_desc: 'You need to update the app to continue using it',
    label_update: 'Update',
    label_result: 'Result',
    label_results: 'Stats',
    label_date: 'Date',
    label_insert_result: 'Insert a result',
    label_insert_date: 'Insert a date',
    label_insert_metric: 'Insert a metric',
    label_add_metric_result: 'Add metric',
    label_save_metric_result: 'Save metric',
    label_add_new_food: 'Add food',
    label_metric_result_added: 'Result added successfully',
    label_no_result: 'No result inserted',
    label_show_detail_history: 'Show history details',
    label_complete_history: 'Complete History',
    label_exercises: 'Exercises',
    label_exercise: 'Exercise',
    label_n_exercises: '{0} exercises',
    label_execution: 'Execution',
    label_informations: 'Informations',
    label_message: 'Message',
    label_comments: 'Comments',
    label_attachments: 'Attachments',
    label_attachment: 'Attachment',
    label_write_a_comment: 'Write a comment',
    label_add_media: 'Add images/videos',
    label_description: 'Description',
    label_load_description: 'Upload a description',
    label_load_multimedia: 'Upload media',
    label_load_progress: 'Progress Upload',
    label_media_added: 'Media uploaded successfully',
    label_progress_added: 'Progress uploaded successfully',
    label_progress_deleted: 'Progress deleted',
    label_delete: 'Delete',
    label_multimedia: 'Media',
    label_progresses: 'Progress',
    label_reservations: 'Reservations',
    label_day_availability: 'Day availability',
    label_add_progress: 'New progress',
    label_metric: 'Metric',
    label_metrics: 'Metrics',
    label_add: 'Add',
    label_front_photo: 'Front photo',
    label_side_photo: 'Side photo',
    label_back_photo: 'Back photo',
    label_load_front_photo: 'Upload front photo',
    label_load_side_photo: 'Upload side photo',
    label_load_back_photo: 'Upload back photo',
    label_medias_and_documents: 'Medias and documents',
    label_search: 'Search',
    label_search_exercise: 'Search exercise',
    label_image: 'Image',
    label_video: 'Video',
    label_file: 'File',
    label_files: 'Files',
    label_set: 'Set',
    label_add_set: 'Add set',
    label_time: 'Time',
    label_ramp: 'Ramp',
    label_reps: 'Repetitions',
    label_reps_short: 'Reps',
    label_min: 'min',
    label_sec: 'sec',
    label_rest: 'Rest',
    label_rest_long: 'Rest',
    label_timer: 'Timer',
    label_no_rest: 'No rest',
    label_hide_execution: 'Hide execution',
    label_notes: 'Notes',
    label_workouts: 'Workout',
    label_plan: 'Plan',
    label_overall: 'Overall',
    label_all: 'All',
    label_load: 'Upload',
    label_load_more: 'Upload more',
    label_nutrition: 'Nutrition',
    label_nutritional_advice: 'Nutritional Advice',
    label_meal_plans: 'Meal plans',
    label_meal_plan: 'Meal plan',
    label_meal_plan_info: 'Informazioni peal',
    label_macros: 'Macros',
    label_shopping_list: 'Shopping List',
    label_weights_history: 'Weight history',
    label_add_weight_result: 'Add weights',
    label_add_note: 'Add note',
    label_save_weight_result: 'Save',
    label_weight_result_added: 'Weights added successfully',
    label_weight_kg: 'Weight (Kg)',
    label_insert_note: 'Insert note',
    label_insert_general_note: 'Insert general note of the exercise',
    label_retry: 'Retry',
    label_language: 'Language',
    label_superset: 'Superset',
    label_forgotten_password: 'Password forgotten?',
    label_confirm: 'Confirm',
    label_send: 'Send',
    label_contact: 'Contact',
    label_start_workout: 'Start workout',
    label_pause: 'Pause',
    label_play: 'Play',
    label_finish: 'Finish',
    label_close: 'Close',
    label_work: 'Work: ',
    label_rest_two_points: 'Rest: ',
    label_start_exercise: 'Start exercise',
    label_new_set: 'New set',
    label_save_history: 'Save to history',
    label_recovers: 'Recover Workout',
    label_insert_food_name: 'Insert food name',
    label_purchased: 'Buyed',
    label_to_buy: 'To buy',
    label_additional_note: 'Additional notes',
    label_reserve: 'Reserve',
    label_reserved: 'Reserved',
    label_reserved_plural: 'Reserved',
    label_time_to_cancel_expired: 'Time for cancellation\nhas expired',
    label_time_to_booking_expired: 'Time for booking\nhas expired',
    label_sold_out: 'Sold Out',
    label_my_reservations: 'My reservations',
    label_week: 'Week',
    label_day: 'Day',
    label_start: 'Start',
    label_end: 'End',
    label_monday: 'Monday',
    label_tuesday: 'Tuesday',
    label_wednesday: 'Wednesday',
    label_thursday: 'Thursday',
    label_friday: 'Friday',
    label_saturday: 'Saturday',
    label_sunday: 'Sunday',
    label_calories: 'Calories',
    label_carbs: 'Carb.',
    label_proteins: 'Proteins',
    label_lipids: 'Lipids',
    label_or: 'or',
    label_from_visit: 'FROM VISIT',
    label_compare: 'Compare',
    label_compare_images: 'Compare images',
    label_compare_images_slider: 'Compare images slider',
    label_show_info: 'Show information',
    label_hide_info: 'Hide information',
    label_upload_attachment: 'Upload attachment',
    label_insert_message: 'Insert message',
    label_document: 'Document',
    label_camera: 'Camera',
    label_gallery_and_video: 'Photos and videos',
    label_surveys: 'Surveys',
    label_survey: 'Survey',
    label_discount_codes: 'Discount codes',
    label_insert_value: 'Insert value',
    label_survey_completed: 'Survey completed successfully',
    label_skip: 'Skip',
    label_fill_in_later: 'Fill in later',
    label_welcome: 'Welcome',
    label_check_in: 'Check In',
    label_fill_in_the_required_answers: 'Fill in the required answers',
    label_specific: 'Specific',
    label_not_editable: '(non editable)',
    label_very_easy: 'Very easy',
    label_easy: 'Easy',
    label_medium: 'Medium',
    label_hard: 'Hard',
    label_very_hard: 'Very hard',
    label_your_time: 'Your time',
    label_chat: 'Chat',
    label_no_message: 'No message',
    label_personal: 'Personal',
    label_program: 'Program',

    strings_profile_edit_success: 'Profile saved successfully',
    strings_empty_to_do_workouts: 'No workout scheduled',
    strings_empty_meal_plans: 'No meal plans assigned',
    strings_empty_macros: 'No macros assigned',
    strings_empty_completed_workouts: 'No complete workout',
    strings_empty_executions: 'No execution',
    strings_empty_reminders: 'No reminders',
    strings_confirm_mark_completed_workout:
      'Do you want to mark the workout as completed?',
    strings_confirm_mark_todo_workout:
      'Do you want to mark the workout as "to do"?',
    strings_confirm_delete_progress: 'Do you want to delete these progress?',
    strings_confirm_delete_result: 'Do you want to delete this result?',
    strings_empty_metrics: 'Empty metrics',
    strings_empty_visits: 'Empty visits',
    strings_empty_media: 'No file uploaded',
    strings_unavailable_chat: 'Chat not available',
    strings_empty_nutritional_advices: 'No nutritional advice uploaded',
    strings_empty_shopping_list: 'No food entered',
    strings_empty_progress: 'No progress uploaded',
    strings_empty_info: 'No additionally information',
    strings_empty_reservations: 'No reservations available',
    strings_empty_programs: 'No workout program assigned',
    strings_empty_conversations: 'No conversation',
    strings_empty_weight: 'No weight inserted',
    strings_empty_weight_look_history:
      'No weight inserted for this execution type \n\n Take a look at the {0} above',
    strings_empty_note: 'No note inserted',
    strings_empty_note_look_history:
      'No note inserted for this execution type \n\n Take a look at the {0} above',
    strings_other_workouts: 'There are {0} workout left to do',
    strings_other_workouts_info: 'Workouts will be visible over the weeks',
    strings_confirm_add_weights_different_set:
      'The number of the added sets is different from those of the exercise. Do you want to add them?',
    strings_confirm_delete_weights:
      'Are you sure you want to delete these weights?',
    strings_initial_state_error_desc:
      'An error occurred during the initialization of the app, please try again.',
    strings_forgotten_password_desc:
      'We will send you an email to reset your password',
    strings_email_recovery_sent_succesfull: 'Password reset email sent',
    strings_disabled_user:
      'You have been deactivated by your coach, contact him for more information',
    strings_workouts_not_done:
      'There are {0} workouts not completed yet, get them back ASAP',
    strings_workout_not_done:
      'There is {0} unfinished workout, get it back ASAP',
    strings_no_reservations_available_on_date:
      'There are no reservations available for this date',
    strings_write_reservation_message: 'Leave blank to not send any messages',
    strings_empty_surveys: 'No surveys',
    strings_empty_questions: 'No questions',
    strings_how_did_you_find_the_workout: 'How did you find the workout?',
    strings_trim_video_error: 'Trimmed videos must be 60 seconds or less.',
  },
});
